### ISSUE TITLE
Add getLockTargetState and getLockCurrentState functions

### ISSUE THREAD

**Issue by philhar88** [Tommrodrigues/homebridge-http-lock-mechanism#2]
Would be great if I could add the ability to get the current/target state via HTTP request also. 

See here:
https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js

**Comment by phenotypic** [comment]
Totally agree with you, I'll look to integrate that as soon as possible.

**Comment by phenotypic** [comment]
Hey @philhar88 

I've made a new repository called [homebridge-web-lock](https://github.com/Tommrodrigues/homebridge-web-lock) which allows for the functionality you were requesting. Everything is explained in the README, but the basic premise is quite similar to this repository with the exception that you can now directly contact a listen server that the plugin sets up so you can send real-time changes in state back to homebridge.

Hope this solves your request,
Tom
