### ISSUE TITLE
Digest authentication

### ISSUE THREAD

**Issue by toroff** [Tommrodrigues/homebridge-http-lock-mechanism#5]
Hi! Can you make digest authentication?

**Comment by phenotypic** [comment]
Hi there, could you elaborate more on what you are requesting?

Note that the plugin currently serves my needs and I have no incentive/extra free time at the moment to implement digest authentication. Of course, you are more than welcome to fork the plugin or create a pull request.

**Comment by toroff** [comment]
i have dahua intercom and they need digest autentification for opening door.
