### ISSUE TITLE
issue with plugin since update

### ISSUE THREAD

**Issue by v0r73x** [Tommrodrigues/homebridge-http-lock-mechanism#6]
Hi, 

first I want to say that i like this plugin and used it 1 year without issues. I have a Homematic and created an simulated door opener (it more a door buzzer) which i was able to close and open with 2 different url commands:

![image](https://user-images.githubusercontent.com/48632087/81800494-3687ad00-9513-11ea-8bf2-67b48c692586.png)

since your change i cannot get it work anymore. Can you please help me that i can use your plugin in the future as well ?  I am not a pro in developing so i cannot understand fully how the homematic api can deliver your requested values - will be great if you can support me here - or if possible to let me go back to your previous plugin version - but i dont know how to do it in homebridge ;( 

regards from Berlin,
Robert

**Comment by phenotypic** [comment]
Hi there,

The newest version replaces the user-specified URLs with a standardised API call you can read more about in the `API interfacing` section.

However, if you are unable to change the API to support this standardised call, you may wish to revert to the last version that supports user-specified URLs by running: `npm i homebridge-http-lock-mechanism@1.2.6`
