### ISSUE TITLE
Hikvision (DS-KD8003) ISAPI command

### ISSUE THREAD

**Issue by ayghazali** [Tommrodrigues/homebridge-http-lock-mechanism#7]
Can someone teach me how to add the function of open door/relay for hikvision doorbells?

I found this [home assistant thread ](https://community.home-assistant.io/t/ds-kd8003-ds-kv8113-ds-kv8213-ds-kv6113-ds-kv8413-and-integration-hikvision-hikconnect-video-intercom-doorbell/238535) discussing this and they had this command for open door

To open an electrical door (relay 1 or 2)
curl -i --digest -u admin:xxx -X PUT -d '<RemoteControlDoor><cmd>open</cmd></RemoteControlDoor>' http://192.168.0.xx/ISAPI/AccessControl/RemoteControl/door/1

Not sure if this can be implemented into this plug-in or any other plugin. 

I tried putting in the URL with the IP of the door station.

Also added username and password options.

I get this error in reuturn:
[08/07/2021, 17:20:23] [HTTPLock] Error getting status: connect ECONNREFUSED 192.168.9.22:80
Note: I did not add the port in the url. It just appears in the logs

Apologies for the noob question, I'm not a coder, so I don't know how these things work exactly

**Comment by phenotypic** [comment]
Hi there, apologies for taking so long to get back to you about your issue. Unfortunately, as I mentioned in your other issue (#5), I would need more information on the specifics of how the digest authentication would need to be implemented. 

Similarly, as I do not have the device you are referring to, it would be very difficult for me to add support without having one to test with.

Please feel free to fork this plugin and make the necessary changes to support your device.
